### ISSUE TITLE
BROTLI Module not found

### ISSUE THREAD

**Issue by alexvuta** [dsteinkopf/kong-response-string-replace#2]
Hello,

I try to install the plugin but on runtime it is not able to find brotli from : 
`
local brotlienc = require "brotli.encoder"
local brotlidec = require "brotli.decoder"
`
Do you have a guide for installing this?
I tried with `luarocks install luajit-brotli` but it is not able to find shared modules (also tried to compile brodli inside dockerfile based on bitnami kong:2.1.4).

![image](https://user-images.githubusercontent.com/11159607/105708621-62ba5100-5f1d-11eb-8a0f-dc00d1ef7794.png)

Thanks!

**Comment by alexvuta** [comment]
Solved with: 

- apt install brotli libbrotli1 libbrotli-dev
- luarocks install luajit-brotli

Maybe this can be specified in README :)

**Comment by dsteinkopf** [comment]
Glad you solved it yourself. May I ask you to provide a PR for an updated README? Thank you very much.
